# Generated by Django 6.0 on 2026-04-05 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0008_member_email_and_suspension'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('overdue', 'Overdue books'), ('reservation_approved', 'Reservation approved'), ('book_available', 'Book available'), ('pending_fines', 'Pending fines'), ('suspension_warning', 'Suspension warning'), ('general', 'General')], db_index=True, max_length=40)),
                ('channel', models.CharField(choices=[('email', 'Email')], db_index=True, max_length=16)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('prepared', 'Prepared')], db_index=True, default='prepared', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='members.member')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
