# Generated by Django 6.0 on 2026-03-05 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('shelf_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('dewey_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=200)),
                ('publish_place', models.CharField(max_length=200)),
                ('publish_year', models.IntegerField()),
                ('edition', models.CharField(max_length=50)),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(max_length=50)),
                ('pages', models.IntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('description', models.TextField()),
                ('authors', models.ManyToManyField(to='books.author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category')),
            ],
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('available', 'متوفر'), ('borrowed', 'مستعار'), ('reserved', 'محجوز'), ('damaged', 'تالف')], default='available', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
