# Generated by Django 6.0 on 2026-03-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
