# Generated by Django 6.0 on 2026-03-24 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_search_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='book',
            new_name='books_book_title_28b4f4_idx',
            old_name='books_book_title_view_idx',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='books_book_languag_a1c621_idx',
            old_name='books_book_lang_year_idx',
        ),
    ]
