# Generated by Django 6.0 on 2026-03-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_bookcopy_print_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookcopy',
            new_name='books_bookc_book_id_65d238_idx',
            old_name='books_copy_qr_idx',
        ),
    ]
