# Generated by Django 6.0 on 2026-04-12 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_remove_unused_seeded_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='books_book_isbn_54becd_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['doi'], name='books_book_doi_59ea63_idx'),
        ),
    ]
