# Generated by Django 6.0 on 2026-04-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_book_books_book_isbn_54becd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_doi_59ea63_idx',
        ),
        migrations.RemoveField(
            model_name='book',
            name='doi',
        ),
    ]
