# Generated by Django 6.0 on 2026-03-06 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_publisher_and_more'),
        ('digital_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='books/pdfs/')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.DeleteModel(
            name='DigitalBook',
        ),
    ]
