# Generated by Django 6.0 on 2026-03-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('overdue', 'استعارة متأخرة'), ('reservation_created', 'طلب حجز جديد'), ('reservation_available', 'كتاب محجوز أصبح متاحًا'), ('high_risk_member', 'إشعار عضو غير ملتزم')], db_index=True, max_length=40),
        ),
    ]
