# Generated by Django 6.0 on 2026-04-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_branding_notification_member_and_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('overdue', 'استعارة متأخرة'), ('reservation_created', 'طلب حجز جديد'), ('reservation_approved', 'حجز تمت الموافقة عليه'), ('reservation_available', 'كتاب محجوز أصبح متاحًا'), ('high_risk_member', 'إشعار عضو غير ملتزم'), ('pending_fine', 'غرامات غير مدفوعة'), ('suspended_member', 'عضو موقوف')], db_index=True, max_length=40),
        ),
    ]
