# Generated by Django 6.0 on 2026-04-05 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulations', '0006_borrowing_created_by_and_finepayment'),
        ('dashboard', '0004_alter_notification_notification_type'),
        ('members', '0008_member_email_and_suspension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermessagelog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_message_logs', to='members.member'),
        ),
        migrations.AlterField(
            model_name='membermessagelog',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_messages', to='dashboard.notification'),
        ),
        migrations.AlterField(
            model_name='membermessagelog',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_sent_member_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='borrowing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_notification_set', to='circulations.borrowing'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_notification_set', to='members.member'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_notification_set', to='circulations.reservation'),
        ),
    ]
