# Generated by Django 6.0 on 2026-04-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_membermessagelog_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='borrowing',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='member',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='reservation',
        ),
        migrations.DeleteModel(
            name='MemberMessageLog',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
