# Generated by Django 6.0 on 2026-03-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('membership_number', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('member_type', models.CharField(choices=[('student', 'طالب'), ('staff', 'موظف'), ('faculty', 'هيئة تدريس')], max_length=20)),
                ('university_id', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('workplace', models.CharField(blank=True, max_length=200, null=True)),
                ('membership_expiry', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
