# Generated by Django 6.0 on 2026-03-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='barcode',
            new_name='barcode_or_qr',
        ),
        migrations.RemoveField(
            model_name='member',
            name='qr_code',
        ),
    ]
