# Generated by Django 6.0 on 2026-03-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
