# Generated by Django 6.0 on 2026-04-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_email_and_suspension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('student', 'طالب'), ('faculty', 'هيئة تدريس')], max_length=20),
        ),
    ]
