# Generated by Django 6.0 on 2026-04-05 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circulations', '0006_borrowing_created_by_and_finepayment'),
        ('members', '0008_member_email_and_suspension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('overdue', 'استعارة متأخرة'), ('reservation_created', 'طلب حجز جديد'), ('reservation_approved', 'حجز تمت الموافقة عليه'), ('reservation_available', 'كتاب محجوز أصبح متاحًا'), ('high_risk_member', 'إشعار عضو غير ملتزم'), ('pending_fine', 'غرامات غير مدفوعة'), ('suspended_member', 'عضو موقوف')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrowing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circulations.borrowing')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circulations.reservation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
